controller:
  kind: Deployment
  replicaCount: 2
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/location: hel1
      load-balancer.hetzner.cloud/name: "http-lb"